### ISSUE TITLE
Broken / Messed up FBX-Files (Characters)

### ISSUE THREAD

**Issue by SonOfKorriban** [Ben1138/MSH2FBX#4]
Hola from germany,
after converting my beloved MiniMag Launcher in FBX sucessfully, i tried to do that with characters also.
Unfortunateley, the result is completeley broken. 
Thats the "imp_inf_shocktrooper.fbx", made of the "imp_inf_shocktrooper.msh"-file from the original 2004 Battlefront game.

![image](https://github.com/user-attachments/assets/d08de6e5-037f-40a4-8d26-f649ed5f48da)

if i try to attach some textures, it's even scarier:
![image](https://github.com/user-attachments/assets/319356e1-d2f8-4846-9f8c-1ffaab3bf946)

am i missing something?
i've used this command to extract them:
MSH2FBX.exe -m imp_inf_shocktrooper.msh 

Any idea, how to fix this? Weapons and vehicles seems to work without any issues:

![image](https://github.com/user-attachments/assets/e0bb4b83-6a45-4613-b8ed-1aae52dcf722)

By the Way: THANK YOU FOR YOUR WORK!!

**Comment by Ben1138** [comment]
You're missing the basepose, see example in README.md.

This command should work: 
`MSH2FBX.exe -m Z:/BF2_ModTools/assets/sides/imp/msh/imp_inf_shocktrooper.msh -b Z:/BF2_ModTools/assets/Animations/SoldierAnimationBank/human_0/basepose.msh -d imp_inf_shocktrooper.fbx -i Mesh_Lowrez Mesh_ShadowVolume`.

Just replace the path to your `BF2_ModTools` respectivly.

If you want animations to be included:
`MSH2FBX.exe -m Z:/BF2_ModTools/assets/sides/imp/msh/imp_inf_shocktrooper.msh -b Z:/BF2_ModTools/assets/Animations/SoldierAnimationBank/human_0/basepose.msh -oa "Z:/BF2_ModTools/assets/Animations/SoldierAnimationBank/human_0" -d imp_inf_shocktrooper.fbx -i Mesh_Lowrez Mesh_ShadowVolume`

![grafik](https://github.com/user-attachments/assets/100a3d43-bfb1-4de2-81a5-7552a7f85e0f)

**Comment by SonOfKorriban** [comment]
Hi again,
as i said, i am using the assets from the first Battlefront game (2004)
There are multiple basepose.msh files in SWBF1ModTools\Assets\Shipped Common Animations.
Which one i should use? I tried some of them (basepose.msh in Human_Bank_0-Folder and human_bazooka_stand_shoot.msh in Human-Folder),  and it still doesn't work, unfortunateley. 

i don't find any animation msh files in the original lvl-files at all. (i looked in all.lvl, common.lvl, imp.lvl, impshell.lvl and shell.lvl)

**Comment by Ben1138** [comment]
Ah I missed the SWBF1 part. In that case, use the `basepose.msh` from `Human_Bank_0` in `Shipped Common Animations`:

`MSH2FBX.exe -m "Z:/BFBuilder/Assets/Sides/IMP/MSH/imp_inf_shocktrooper.msh" -b "Z:/BFBuilder/Assets/Shipped Common Animations/Human_Bank_0/basepose.msh" -i Mesh_Lowrez Mesh_ShadowVolume -d imp_inf_shocktrooper.fbx`
![grafik](https://github.com/user-attachments/assets/e15a335d-bcdd-449c-a22b-6f4d6b12bd80)
When including animations and trying to play them back, the **rigging seems indeed to be broken**, while the basepose is still intact. If you need animations, you could try and check whether the [Blender plugin](https://github.com/PrismaticFlower/SWBF-msh-Blender-IO) already supports animation import (not sure about that) or use it instead of MSH2FBX.

https://github.com/user-attachments/assets/6928e531-243e-4015-895f-baa944eaaceb

**Comment by SonOfKorriban** [comment]
Got it. Thanks!
![image](https://github.com/user-attachments/assets/410cb560-5054-4587-b0be-6151a40fb66e)
